### ISSUE TITLE
About gpu in logisim

### ISSUE THREAD

**Issue by BobBogart** [Caian/tinygpu#1]
Hello Caian!I find it out that the logisim Italian fork can't run gpu,could you please share your whole logisim here?
                                   Best wishes from BobBogart
@Caian

**Comment by Caian** [comment]
Hello Bob, this circuit was made using logisim evolution available here: https://github.com/reds-heig/logisim-evolution I tested it with the latest stable version 3.4.1.

**Comment by BobBogart** [comment]
Hello Caian,Thank you very much!
